server.port: 9090

spring:
  application.name: shareItServer
  main.banner-mode: OFF
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC
  sql.init.mode: always
  datasource:
    username: shareit
    password: shareit
    url: "jdbc:postgresql://localhost:5432/shareit"
    driver-class-name: "org.postgresql.Driver"

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: shareit
    password: shareit
    url: "jdbc:h2:mem:shareit"
    driver-class-name: "org.h2.Driver"

---
logging.level.org.springframework:
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: DEBUG
